spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
sales-order:
  exchange:
    name: sales-order-exchange
     
  queue:
    name: sales-order-queue
  routing: 
    key: sales-order-routing-key